export enum WindowOverlayId {
  LAYOUT_OVERLAY = "layoutoverlay",
  ADVANCED_PANEL_OVERLAY = "advancedpanel",
  BOOSTBOX_OVERLAY = "boostbox",
  CHATRACE_GAME_STANDINGS = "chatracegamestandings",
  CHATRACE_GAME = "chatracegame",
  DATABLOCK_OVERLAY = "datablock",
  FLAGS_OVERLAY = "flags",
  FLATMAP_OVERLAY = "flatmap",
  TRACKMAP_OVERLAY = "trackmap",
  MINIMAP_OVERLAY = "minimap",
  FUELCALCULATOR_OVERLAY = "fuelcalculator",
  HEAD2HEAD_OVERLAY = "head2head",
  INPUT_TELEMETRY_OVERLAY = "inputtelemetry",
  RADAR_OVERLAY = "radar",
  RELATIVE_OVERLAY = "relative",
  STANDINGS_OVERLAY = "standings",
  CHAT_OVERLAY = "chat",
  CHAT_HIGHLIGHT_OVERLAY = "chathighlight",
  PITBOX_HELPER_OVERLAY = "pitboxhelper",
  HORIZONTAL_STANDINGS_OVERLAY = "horizontalstandings",
  MIC_VISUALIZER_OVERLAY = "micvisualizer",
  CUSTOM_URL_OVERLAY = "customurl",
  CUSTOM_TEXT_OVERLAY = "customtext",
  LAPTIME_LOG_OVERLAY = "laptimelog",
  LAPTIME_GRAPH_OVERLAY = "laptimegraph",
  RADAR_BARS_OVERLAY = "radarbars",
  BLINDSPOT_OVERLAY = "blindspot",
  DELTA_BAR_OVERLAY = "deltabar",
  LAP_TIMING_OVERLAY = "laptiming",
  LAP_TIME_SPREAD_OVERLAY = "laptimespread",
  SESSION_TIMER_OVERLAY = "sessiontimer",
  HEARTRATE_OVERLAY = "heartrate",
  WEATHER_MONITOR_OVERLAY = "weathermonitor",

  // non-overlay mode overlays
  GARAGECOVER_OVERLAY = "garagecover",
}

// this should not be changed because VR overlays are detected by these defined names
export enum WindowOverlayTitle {
  LAYOUT_OVERLAY = "Layout Overlay",
  ADVANCED_PANEL_OVERLAY = "Advanced Panel Overlay",
  BOOSTBOX_OVERLAY = "Boost Box Overlay",
  CHATRACE_GAME = "Chat Race Game",
  CHATRACE_GAME_STANDINGS = "Chat Race Game Standings",
  DATABLOCK_OVERLAY = "Data Block Overlay",
  FLAGS_OVERLAY = "Flags Overlay",
  FLATMAP_OVERLAY = "Flat Map Overlay",
  TRACKMAP_OVERLAY = "TrackMap Overlay",
  MINIMAP_OVERLAY = "MiniMap Overlay",
  FUELCALCULATOR_OVERLAY = "Fuel Calculator Overlay",
  HEAD2HEAD_OVERLAY = "Head2head Overlay",
  INPUT_TELEMETRY_OVERLAY = "Input Telemetry Overlay",
  RADAR_OVERLAY = "Radar Overlay",
  RELATIVE_OVERLAY = "Relative Overlay",
  STANDINGS_OVERLAY = "Standings Overlay",
  CHAT_OVERLAY = "Chat Overlay",
  CHAT_HIGHLIGHT_OVERLAY = "Chat Highlight Overlay",
  PITBOX_HELPER_OVERLAY = "Pitbox Helper Overlay",
  HORIZONTAL_STANDINGS_OVERLAY = "Horizontal Standings Overlay",
  MIC_VISUALIZER_OVERLAY = "Audio Motion Overlay",
  CUSTOM_URL_OVERLAY = "Custom Url Overlay",
  CUSTOM_TEXT_OVERLAY = "Custom Text Overlay",
  LAPTIME_LOG_OVERLAY = "LapTime Log Overlay",
  LAPTIME_GRAPH_OVERLAY = "LapTime Graph Overlay",
  GARAGECOVER_OVERLAY = "Garage Cover Overlay",
  RADAR_BARS_OVERLAY = "Radar Bars Overlay",
  BLINDSPOT_OVERLAY = "Blind Spot Overlay",
  DELTA_BAR_OVERLAY = "Delta Bar Overlay",
  LAP_TIMING_OVERLAY = "Lap Timing Overlay",
  LAP_TIME_SPREAD_OVERLAY = "Lap Time Spread",
  SESSION_TIMER_OVERLAY = "Session Timer Overlay",
  HEARTRATE_OVERLAY = "Heart Rate Overlay",
  WEATHER_MONITOR_OVERLAY = "Weather Monitor",
}
